version: '3'

services:
  stock-api:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./上市公司.csv:/app/上市公司.csv
      - ./上櫃公司.csv:/app/上櫃公司.csv
      - ./brokers.json:/app/brokers.json
    networks:
      - web
      - internal

networks:
  web:
    external: true
  internal:
    internal: true